const ACTIONS = {
  // LICENSE
  UPDATE_LICENSE: 'UPDATE_LICENSE',
  // LEVEL
  ADD_LEVEL: 'ADD_LEVEL',
  REMOVE_LEVEL: 'REMOVE_LEVEL',
  UPDATE_LEVEL: 'UPDATE_LEVEL',
  // STEP
  ADD_STEP: 'ADD_STEP',
  UPDATE_STEP: 'UPDATE_STEP',
  REMOVE_STEP: 'REMOVE_STEP',
  MOVE_STEP: 'MOVE_STEP',

  // STEP DRAG AND DROP
  ADD_STEP_PLACEHOLDER: 'ADD_STEP_PLACEHOLDER',
  REMOVE_STEP_PLACEHOLDER: 'REMOVE_STEP_PLACEHOLDER',
  REPLACE_STEP_PLACEHOLDER: 'REPLACE_STEP_PLACEHOLDER',
};

export default ACTIONS;
