const ACTIONS = {
  ADD_LEVEL_TO_LICENSE: 'ADD_LEVEL_TO_LICENSE',
  LICENSE_INFO_CHANGE: 'LICENSE_INFO_CHANGE',
  LEVEL_CHANGE: 'LEVEL_CHANGE',
  REMOVE_LEVEL: 'REMOVE_LEVEL',
  ADD_STEP_TO_LEVEL: 'ADD_STEP_TO_LEVEL',
  REMOVE_STEP_FROM_LEVEL: 'REMOVE_STEP_FROM_LEVEL',
};

export default ACTIONS;
