const AUTH_ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  LOGOUT_ACTION: 'LOGOUT_ACTION',
  AUTH_REQUEST_FETCHING: 'AUTH_REQUEST_FETCHING',
  AUTH_REQUEST_SUCCESS: 'AUTH_REQUEST_SUCCESS',
  AUTH_REQUEST_FAILED: 'AUTH_REQUEST_FAILED',
};

export default AUTH_ACTION_TYPES;
