const ACTIONS = {
  ANSWER_INFO_CHANGE: 'ANSWER_INFO_CHANGE',
  QUESTION_INFO_CHANGE: 'QUESTION_INFO_CHANGE',
  ADD_QUESTION: 'ADD_QUESTION',
  REMOVE_QUESTION: 'REMOVE_QUESTION',
  ADD_ANSWER: 'ADD_ANSWER',
  REMOVE_ANSWER: 'REMOVE_ANSWER',
  CREATE_QUIZ: 'CREATE_QUIZ',
  SET_CORRECT_ANSWER: 'SET_CORRECT_ANSWER',
};

export default ACTIONS;
