export const QUESTION_TYPE = {
  VIDEO: 'VIDEO',
  FILE_UPLOAD: 'FILE_UPLOAD',
  AGREEMENT: 'AGREEMENT',
};

export const RESPONSE_TYPE = {
  INITIAL: 'INITIAL',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};
